import { useMemo, useRef, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { motion, AnimatePresence } from 'framer-motion'
import { useApp } from '../store/AppStore'
import { Icon, Badge, Modal, ProgressBar } from '../components/ui'

const SOURCE_META = {
  typed: { label: 'Typed', icon: 'keyboard' },
  handwritten: { label: 'Handwritten', icon: 'stylus' },
  photo: { label: 'Photo', icon: 'photo_camera' },
  ai_organized: { label: 'AI Organized', icon: 'auto_awesome' },
}

// ---------- Upload flow (PRD §5.4) ----------
function UploadModal({ open, onClose }) {
  const { addNote, showToast } = useApp()
  const [stage, setStage] = useState('idle') // idle | processing | done
  const [progress, setProgress] = useState(0)
  const [fileName, setFileName] = useState('')
  const timerRef = useRef(null)

  const startUpload = (name) => {
    setFileName(name)
    setStage('processing')
    setProgress(0)
    let p = 0
    timerRef.current = setInterval(() => {
      p += 8 + Math.random() * 10
      if (p >= 100) {
        clearInterval(timerRef.current)
        setProgress(100)
        setTimeout(() => setStage('done'), 300)
      } else setProgress(p)
    }, 220)
  }

  const confirm = () => {
    addNote({
      id: `n-${Date.now()}`,
      title: fileName.replace(/\.[^.]+$/, ''),
      folderId: 'f-math-ch7',
      folderPath: 'A-Level Math / Ch7 Calculus',
      tags: ['uploaded'],
      linkedTopics: ['calculus-extrema'],
      linkedErrors: [],
      source: 'photo',
      createdAt: new Date().toISOString().slice(0, 10),
      updatedAt: new Date().toISOString().slice(0, 10),
      content: [
        { t: 'p', v: `Note generated by OCR from "${fileName}". The AI has auto-classified it and linked the relevant topics.` },
        { t: 'p', v: '(Recognised content will appear here — text, images and formulas supported.)' },
      ],
      aiSuggestions: [{ type: 'link_topic', message: 'Recognised content matches syllabus Unit 7.2 — topic auto-linked.' }],
    })
    showToast('Note created and classified by AI', 'success')
    onClose()
    setStage('idle')
  }

  return (
    <Modal open={open} onClose={() => { onClose(); setStage('idle') }} title="Upload note file">
      {stage === 'idle' && (
        <div>
          <label className="border-2 border-dashed border-warm-stone/30 rounded-card p-10 flex flex-col items-center gap-2 cursor-pointer hover:border-deep-teal hover:bg-teal-tint/40 transition-colors">
            <Icon name="cloud_upload" size={36} className="text-deep-teal" />
            <p className="text-sm font-medium">Click to select or drag a file here</p>
            <p className="text-xs text-warm-stone">Supported: photos (handwritten notes) / PDF / screenshots</p>
            <input type="file" className="hidden" accept="image/*,.pdf" onChange={(e) => e.target.files[0] && startUpload(e.target.files[0].name)} />
          </label>
          <button className="zb-btn-ghost w-full mt-3" onClick={() => startUpload('handwritten-notes-ch7.jpg')}>Try the flow with a demo file</button>
        </div>
      )}

      {stage === 'processing' && (
        <div className="py-8 text-center">
          <p className="text-sm text-warm-stone mb-3">Recognising the content of "{fileName}"…</p>
          <ProgressBar value={progress} className="max-w-xs mx-auto" />
          <p className="font-mono text-xs text-warm-stone mt-2">{Math.min(100, Math.round(progress))}%</p>
          <p className="text-xs text-warm-stone mt-4">OCR recognition → subject detection → chapter classification</p>
        </div>
      )}

      {stage === 'done' && (
        <div>
          <div className="bg-teal-tint border border-deep-teal/30 rounded-comp p-4 mb-4">
            <p className="text-sm font-medium text-deep-teal flex items-center gap-1.5 mb-1">
              <Icon name="check_circle" size={16} /> Recognition complete
            </p>
            <p className="text-sm">Recognised as: <span className="font-semibold">A-Level Math — Chapter 7 Trigonometry / Calculus</span></p>
          </div>
          <div className="flex gap-2">
            <button className="zb-btn-primary flex-1" onClick={confirm}>Confirm & create note</button>
            <button className="zb-btn-ghost flex-1" onClick={() => { showToast('You can pick the folder manually in the classification tree', 'info') }}>Change folder</button>
          </div>
        </div>
      )}
    </Modal>
  )
}

// ---------- Note detail ----------
function NoteDetail({ note, errors }) {
  const { updateNote, showToast } = useApp()
  const [title, setTitle] = useState(note.title)
  const [organizing, setOrganizing] = useState(false)
  const linkedErrors = errors.filter((e) => note.linkedErrors.includes(e.id))

  const renderBlock = (b, i) => {
    if (b.t === 'h') return <h4 key={i} className="font-semibold mt-4 mb-2">{b.v}</h4>
    if (b.t === 'formula') {
      return <div key={i} className="bg-warm-paper border border-whisper-line rounded-comp px-4 py-3 my-3 math text-[15px]">{b.v}</div>
    }
    return <p key={i} className="text-sm leading-7 text-deep-ink mb-2.5">{b.v}</p>
  }

  const organize = () => {
    setOrganizing(true)
    setTimeout(() => {
      updateNote(note.id, { tags: [...new Set([...note.tags, 'organized'])], source: 'ai_organized' })
      setOrganizing(false)
      showToast('AI organisation complete: topics linked and structure optimised', 'success')
    }, 1200)
  }

  return (
    <div className="flex-1 overflow-y-auto">
      <input
        className="text-xl font-bold tracking-tight w-full bg-transparent focus:outline-none mb-1"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        onBlur={() => title !== note.title && updateNote(note.id, { title })}
      />
      <div className="flex items-center gap-2 text-xs text-warm-stone mb-4 flex-wrap">
        <span>{note.folderPath}</span>
        <span>·</span>
        <span className="font-mono">{note.createdAt} created · {note.updatedAt} edited</span>
        <span className="zb-badge bg-warm-stone/10 text-warm-stone gap-1">
          <Icon name={SOURCE_META[note.source].icon} size={12} /> {SOURCE_META[note.source].label}
        </span>
      </div>

      {/* Toolbar */}
      <div className="flex items-center gap-1 pb-3 mb-4 border-b border-whisper-line">
        {[['format_bold', 'Bold'], ['format_italic', 'Italic'], ['format_list_bulleted', 'List'], ['image', 'Image'], ['functions', 'Formula'], ['highlight', 'Highlight']].map(([icon, label]) => (
          <button key={icon} title={label} className="p-2 rounded-comp text-warm-stone hover:text-deep-ink hover:bg-teal-tint" onClick={() => showToast(`Demo mode: ${label} will hook into the rich-text editor (Tiptap)`, 'info')}>
            <Icon name={icon} size={18} />
          </button>
        ))}
      </div>

      <div className="pb-4">{note.content.map(renderBlock)}</div>

      {/* Linked errors */}
      {linkedErrors.length > 0 && (
        <div className="border-t border-whisper-line pt-4 mb-4">
          <p className="text-sm font-semibold mb-2 flex items-center gap-1.5">
            <Icon name="bookmarks" size={16} className="text-alert-amber" /> Linked errors ({linkedErrors.length})
          </p>
          <div className="flex flex-col gap-2">
            {linkedErrors.map((e) => (
              <div key={e.id} className="flex items-center justify-between bg-warm-paper rounded-comp px-3 py-2 text-sm">
                <span className="truncate text-warm-stone">{e.questionSummary}</span>
                <Badge tone="amber">{e.status === 'pending_review' ? 'To Review' : e.status === 'mastered' ? 'Mastered' : 'Reviewing'}</Badge>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* AI organisation suggestions */}
      {note.aiSuggestions.length > 0 && (
        <div className="border-t border-whisper-line pt-4">
          <p className="text-sm font-semibold mb-2 flex items-center gap-1.5">
            <Icon name="auto_awesome" size={16} className="text-deep-teal" /> AI Organisation Suggestions
          </p>
          <div className="flex flex-col gap-2 mb-3">
            {note.aiSuggestions.map((s, i) => (
              <div key={i} className="bg-teal-tint/70 rounded-comp px-3 py-2.5 text-sm text-warm-stone leading-6">{s.message}</div>
            ))}
          </div>
          <button className="zb-btn-primary !h-9" onClick={organize} disabled={organizing}>
            {organizing ? 'Organising…' : (<><Icon name="magic_button" size={16} /> One-click organise</>)}
          </button>
        </div>
      )}
    </div>
  )
}

// ---------- Notes page ----------
export default function Notes() {
  const { notes, noteFolders, errors, addNote, showToast } = useApp()
  const { id: routeNoteId } = useParams()
  const navigate = useNavigate()
  const [activeFolder, setActiveFolder] = useState('all')
  const [search, setSearch] = useState('')
  const [uploadOpen, setUploadOpen] = useState(false)
  const [activeId, setActiveId] = useState(routeNoteId || null)

  const filteredNotes = useMemo(() => {
    let list = notes
    if (activeFolder === 'recent') list = [...list].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)).slice(0, 5)
    else if (activeFolder !== 'all') list = list.filter((n) => n.folderId === activeFolder)
    if (search) list = list.filter((n) => n.title.includes(search) || n.tags.some((t) => t.includes(search)))
    return list
  }, [notes, activeFolder, search])

  const activeNote = notes.find((n) => n.id === activeId) || filteredNotes[0]

  const createNote = () => {
    const id = addNote({
      id: `n-${Date.now()}`, title: 'Untitled note', folderId: 'f-math', folderPath: 'A-Level Math',
      tags: [], linkedTopics: [], linkedErrors: [], source: 'typed',
      createdAt: new Date().toISOString().slice(0, 10), updatedAt: new Date().toISOString().slice(0, 10),
      content: [{ t: 'p', v: 'Start writing…' }], aiSuggestions: [],
    })
    setActiveId(id)
    showToast('New note created', 'success')
  }

  const FolderItem = ({ folder, depth = 0 }) => (
    <>
      <button
        className={`w-full flex items-center justify-between px-2.5 py-1.5 rounded-comp text-sm transition-colors ${activeFolder === folder.id ? 'bg-teal-tint text-deep-teal font-medium' : 'text-deep-ink hover:bg-warm-paper'}`}
        style={{ paddingLeft: `${10 + depth * 14}px` }}
        onClick={() => setActiveFolder(folder.id)}
      >
        <span className="flex items-center gap-1.5 truncate">
          {depth === 0 && <Icon name="folder" size={15} className="text-warm-stone" />}
          {folder.name}
        </span>
        <span className="font-mono text-xs text-warm-stone">{folder.noteCount}</span>
      </button>
      {folder.children?.map((c) => <FolderItem key={c.id} folder={c} depth={depth + 1} />)}
    </>
  )

  return (
    <div className="max-w-max-width mx-auto px-4 lg:px-6 py-6">
      <div className="flex items-center justify-between mb-4 flex-wrap gap-3">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">My Notes</h1>
          <p className="text-xs text-warm-stone mt-0.5">{notes.length} notes · AI auto-classification & linking</p>
        </div>
        <div className="flex items-center gap-2">
          <div className="relative">
            <Icon name="search" size={16} className="absolute left-2.5 top-1/2 -translate-y-1/2 text-warm-stone" />
            <input className="zb-input !w-52 !pl-8" placeholder="Search notes…" value={search} onChange={(e) => setSearch(e.target.value)} />
          </div>
          <button className="zb-btn-ghost" onClick={() => setUploadOpen(true)}><Icon name="cloud_upload" size={16} /> Upload</button>
          <button className="zb-btn-primary" onClick={createNote}><Icon name="add" size={16} /> New note</button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-[200px_280px_1fr] gap-4 items-start">
        {/* Left: folder tree */}
        <div className="zb-card !p-3 lg:sticky lg:top-20">
          <p className="text-xs font-semibold text-warm-stone uppercase tracking-wide px-2 mb-1.5">Library</p>
          <button className={`w-full flex items-center justify-between px-2.5 py-1.5 rounded-comp text-sm mb-0.5 ${activeFolder === 'all' ? 'bg-teal-tint text-deep-teal font-medium' : 'hover:bg-warm-paper'}`} onClick={() => setActiveFolder('all')}>
            <span className="flex items-center gap-1.5"><Icon name="description" size={15} className="text-warm-stone" />All notes</span>
            <span className="font-mono text-xs text-warm-stone">{notes.length}</span>
          </button>
          <button className={`w-full flex items-center justify-between px-2.5 py-1.5 rounded-comp text-sm mb-2 ${activeFolder === 'recent' ? 'bg-teal-tint text-deep-teal font-medium' : 'hover:bg-warm-paper'}`} onClick={() => setActiveFolder('recent')}>
            <span className="flex items-center gap-1.5"><Icon name="schedule" size={15} className="text-warm-stone" />Recently edited</span>
            <span className="font-mono text-xs text-warm-stone">5</span>
          </button>
          <p className="text-xs font-semibold text-warm-stone uppercase tracking-wide px-2 mb-1.5 mt-3">Subjects</p>
          {noteFolders.map((f) => <FolderItem key={f.id} folder={f} />)}
          <button className="w-full flex items-center gap-1.5 px-2.5 py-1.5 mt-2 rounded-comp text-sm text-warm-stone border border-dashed border-warm-stone/30 hover:border-deep-teal hover:text-deep-teal transition-colors" onClick={() => showToast('The AI creates folders automatically based on note content', 'info')}>
            <Icon name="add" size={15} /> New folder
          </button>
        </div>

        {/* Middle: note list */}
        <div className="zb-card !p-2 lg:sticky lg:top-20 max-h-[75vh] overflow-y-auto">
          <AnimatePresence>
            {filteredNotes.map((n) => (
              <motion.button
                key={n.id}
                layout
                initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
                className={`w-full text-left px-3 py-3 rounded-comp mb-1 transition-colors ${activeNote?.id === n.id ? 'bg-teal-tint' : 'hover:bg-warm-paper'}`}
                onClick={() => setActiveId(n.id)}
              >
                <div className="flex items-center justify-between gap-2">
                  <p className="font-medium text-sm truncate">{n.title}</p>
                  {n.linkedErrors.length > 0 && <Badge tone="amber">{n.linkedErrors.length} errors</Badge>}
                </div>
                <p className="text-xs text-warm-stone mt-1 line-clamp-2 leading-5">
                  {n.content.find((b) => b.t === 'p')?.v}
                </p>
                <p className="text-[10px] text-warm-stone/70 font-mono mt-1.5">{n.updatedAt} · {n.folderPath}</p>
              </motion.button>
            ))}
          </AnimatePresence>
          {filteredNotes.length === 0 && <p className="text-sm text-warm-stone text-center py-8">No matching notes</p>}
        </div>

        {/* Right: detail */}
        <div className="zb-card min-h-[60vh] flex flex-col max-h-[80vh]">
          {activeNote ? (
            <NoteDetail key={activeNote.id} note={activeNote} errors={errors} />
          ) : (
            <p className="text-warm-stone text-sm m-auto">Select a note to view its content</p>
          )}
        </div>
      </div>

      <UploadModal open={uploadOpen} onClose={() => setUploadOpen(false)} />
    </div>
  )
}
